#
# OrangeFox Recovery 配置 — OnePlus Ace5 Ultra (OP60EDL1)
#

FOX_VARIANT := c16
OF_MAINTAINER := SHuiTU68
FOX_BUILD_TYPE := Unofficial

FOX_VENDOR_BOOT_RECOVERY := 1
FOX_VIRTUAL_AB_DEVICE := 1
OF_NO_REFLASH_CURRENT_ORANGEFOX := 1

FOX_RECOVERY_SYSTEM_PARTITION := /dev/block/mapper/system
FOX_RECOVERY_VENDOR_PARTITION := /dev/block/mapper/vendor

FOX_ENABLE_APP_MANAGER := 1
FOX_INSTALLER_DISABLE_AUTOREBOOT := 0
FOX_DELETE_AROMAFM := 1
OF_FLASHLIGHT_ENABLE := 0

FOX_USE_BASH_SHELL := 0
FOX_ASH_IS_BASH := 0
FOX_USE_TAR_BINARY := 0
FOX_USE_LZ4_BINARY := 1
FOX_USE_SED_BINARY := 1
FOX_USE_XZ_UTILS := 0
FOX_USE_ZSTD_BINARY := 0
FOX_USE_NANO_EDITOR := 0
FOX_USE_UPDATED_MAGISKBOOT := 1
FOX_USE_DATE_BINARY := 1
FOX_USE_DMSETUP := 1
OF_USE_AIDL_BOOT_CONTROL := 1

FOX_TARGET_DEVICES := OP60EDL1
TARGET_DEVICE_ALT := OP60EDL1

# 屏幕打孔摄像头位置（Ace5 Ultra 居中打孔，需实测后调整）
# 参考：屏幕宽 1216px，状态栏高度约 118px
OF_SCREEN_H := 2800
OF_STATUS_H := 141
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 1  # 0=左, 1=居中, 2=右
