# Android 14+ lunch choices are declared in AndroidProducts.mk via COMMON_LUNCH_CHOICES.
export FOX_MOVE_MAGISK_INSTALLER_TO_RAMDISK=0
export FOX_ENABLE_KERNELSU_SUPPORT=0
export FOX_ENABLE_KERNELSU_NEXT_SUPPORT=0
export FOX_ENABLE_SUKISU_SUPPORT=0
export FOX_USE_PATCHELF_BINARY=0