# AOSP 14.1: add_lunch_combo 已废弃，使用 AndroidProducts.mk 的 COMMON_LUNCH_CHOICES
# 通过 AndroidProducts.mk 注册编译目标

export FOX_MOVE_MAGISK_INSTALLER_TO_RAMDISK=0
export FOX_ENABLE_KERNELSU_SUPPORT=0
export FOX_ENABLE_KERNELSU_NEXT_SUPPORT=0
export FOX_ENABLE_SUKISU_SUPPORT=0
export FOX_USE_PATCHELF_BINARY=0